name: Build, test, and publish Docker Images

# For more details on events that trigger workflows see:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    paths-ignore:
      - "*.md"
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "*.md"

jobs:
  build-test-publish-images:
    name: Build, test, and publish Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make dev-env

      - name: Get refs - this will be used as tags later on
        shell: bash
        run: |
          echo "::set-output name=sha12::$(echo ${GITHUB_SHA} | cut -c1-12)"
        id: getrefs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker # to be able to test the image locally

      - name: Build # Build only to be able to run tests
        uses: docker/build-push-action@v2
        with:
          context: "."
          file: "Dockerfile"
          tags: |
            toluclassics/transformers_notebook/huggingface_jupyter:latest
          push: false

      - name: Run tests
        run: python -m pytest tests

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: "."
          file: "Dockerfile"
          tags: |
            toluclassics/transformers_notebook/huggingface_jupyter:${{steps.getrefs.outputs.sha12}}, toluclassics/transformers_notebook/huggingface_jupyter:latest
